# Generated by Django 3.2.6 on 2021-11-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_alt_text', models.TextField()),
                ('heading_text', models.TextField(max_length=50)),
                ('blurb_text', models.TextField(max_length=100)),
                ('button_text', models.TextField(max_length=20)),
                ('button_link', models.URLField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.pielist')),
            ],
        ),
    ]
