# Generated by Django 3.2.6 on 2021-11-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitems',
            name='image_url',
            field=models.TextField(),
        ),
    ]
