# Generated by Django 3.2.6 on 2021-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_carouselitems_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitems',
            name='button_link',
            field=models.TextField(),
        ),
    ]
