# Generated by Django 3.2.6 on 2021-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carouselitems_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitems',
            name='is_first',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
