# Generated by Django 3.2.6 on 2021-11-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carouselitems_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitems',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
