# Generated by Django 3.2.6 on 2021-11-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_carouselitems_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselitems',
            old_name='active',
            new_name='show_on_carousel',
        ),
    ]
