# Generated by Django 3.2.6 on 2021-11-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_active_carouselitems_show_on_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='')),
                ('image_alt_text', models.TextField()),
                ('heading_dark_text', models.TextField(max_length=50)),
                ('heading_light_text', models.TextField(max_length=100)),
                ('blurb_text', models.TextField(max_length=200)),
                ('show_on_page', models.BooleanField()),
            ],
        ),
    ]
