# Generated by Django 3.2.6 on 2021-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_featureditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureditems',
            name='left_align',
            field=models.BooleanField(default=True),
        ),
    ]
