# Generated by Django 3.2.6 on 2021-11-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_featureditems_left_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitems',
            name='left_align',
            field=models.BooleanField(default=True),
        ),
    ]
