# Generated by Django 3.2.6 on 2021-11-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_carouselitems_left_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitems',
            name='text_color',
            field=models.TextField(default='text-dark'),
        ),
    ]
