# Generated by Django 3.2.6 on 2021-11-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_carouselitems_text_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselitems',
            old_name='text_color',
            new_name='blurb_text_style',
        ),
        migrations.AddField(
            model_name='carouselitems',
            name='button_style',
            field=models.TextField(default='text-dark'),
        ),
        migrations.AddField(
            model_name='carouselitems',
            name='heading_text_style',
            field=models.TextField(default='text-dark'),
        ),
    ]
