# Generated by Django 3.2.6 on 2021-11-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211102_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='pielist',
            name='blurb_text',
            field=models.TextField(default='text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pielist',
            name='blurb_text_style',
            field=models.TextField(default='text-dark'),
        ),
        migrations.AddField(
            model_name='pielist',
            name='button_link',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pielist',
            name='button_style',
            field=models.TextField(default='btn-primary'),
        ),
        migrations.AddField(
            model_name='pielist',
            name='button_text',
            field=models.TextField(default='Text', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pielist',
            name='heading_text',
            field=models.TextField(default='Text', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pielist',
            name='heading_text_style',
            field=models.TextField(default='text-dark'),
        ),
        migrations.AddField(
            model_name='pielist',
            name='image_alt_text',
            field=models.TextField(default='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pielist',
            name='image_url',
            field=models.ImageField(default='Text', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pielist',
            name='show_on_header',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
