# Generated by Django 3.2.6 on 2021-11-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211103_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapColours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='allergens',
            name='colour',
            field=models.ManyToManyField(to='main.BootstrapColours'),
        ),
    ]
