# Generated by Django 3.2.6 on 2021-11-03 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211103_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergens',
            name='colour',
        ),
        migrations.AddField(
            model_name='allergens',
            name='colour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.bootstrapcolours'),
            preserve_default=False,
        ),
    ]
