# Generated by Django 3.2.6 on 2021-11-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_bootstrapcolours_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pielist',
            old_name='show_on_header',
            new_name='show_in_shop',
        ),
    ]
