# Generated by Django 3.2.6 on 2021-11-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_show_on_header_pielist_show_in_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pielist',
            name='show_in_shop',
            field=models.BooleanField(default=True),
        ),
    ]
