# Generated by Django 3.2.6 on 2021-11-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_pielist_show_in_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pielist',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
