# Generated by Django 3.2.6 on 2021-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211110_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
